### ISSUE TITLE
Add the ability to specify additional edn readers for config files?

### ISSUE THREAD

**Issue by jskrzypek** [thheller/shadow-cljs#627]
Would it be possible to pass in extra readers to the `edn/read-string :readers` map? I'm imagining something could be pulled in via the `:deps :aliases` (but relatively new to clojure/clojurescript, so maybe that's not feasible)

My problem is that we have several cljs apps that are running in production on different nodes in our cluster and I want to dockerize shadow-cljs processes for our local dev versions. Currently most of us are just running shadow-cljs from our shells or emacs clients, and I want to be able to have docker-compose specify via environment variables which ports shadow-cljs should host the app on as well as opening the nrepl on, but also be able to provide a default if the process is run locally without forcing people to specify the port in the local env, as the example below would require.

I thought that maybe functionality could be added so I could pass in a map of `:readers` in the `:deps :aliases` like I can with `:nrepl`, where I could have a library that provides a reader function, and then I could specify something like `#custom/env-with-default "HTTP_PORT:8231"` that would check System.getenv for `$HTTP_PORT` like `#shadow/env` but fall back to `8231` if no env var with that name is defined, something like

```clj
(defn getenv-with-default 
  [envname-with-default]
  (let [[envname default] (clojure.string/split envname-with-default #":" 1)]
     (or (System/getenv envname) default)))
```

Would something like that be possible?

-----------------------------

### Example of the currently available solution
`/app-client-1/shadow-cljs.edn`
```edn
{:deps {:aliases [:nrepl]}
 :source-paths ["src" "test"]
 :nrepl  {:port #shadow/env "NREPL_PORT_1")
 :builds {:app {:devtools {:http-port #shadow/env "HTTP_PORT_1"}}}}
```

`/app-client-2/shadow-cljs.edn`
```edn
{:deps {:aliases [:nrepl]}
 :source-paths ["src" "test"]
 :nrepl  {:port #shadow/env "NREPL_PORT_2")
 :builds {:app {:devtools {:http-port #shadow/env "HTTP_PORT_2"}}}}
```

`/docker-compose.yml`
```yml
services:
  app-client-1:
    restart: always
    ports:
      - 127.0.0.1:8241:8230
      - 127.0.0.1:8291:8280
    environment:
      NREPL_PORT_1: "8241"
      HTTP_PORT_1: "8291"
    build:
      context: '.'
      dockerfile: 'app-client-1/Dockerfile.local'
    volumes:
      - './shared-components:/app/shared-components'
      - './app-client-1/package.json:/app/app-client-1/package.json'
      - './app-client-1/shadow-cljs.edn:/app/app-client-1/shadow-cljs.edn'
      - './app-client-1/public/assets:/app/app-client-1/public/assets'
      - './app-client-1/public/index.html:/app/app-client-1/public/index.html'
      - './app-client-1/src:/app/app-client-1/src'
    command:
      [
        "npx",
        "shadow-cljs",
        "watch",
        "app",
      ]
  app-client-2:
    restart: always
    ports:
      - 127.0.0.1:8242:8231
      - 127.0.0.1:8292:8281
    environment:
      NREPL_PORT_2: "8242"
      HTTP_PORT_2: "8292"
    build:
      context: '.'
      dockerfile: 'app-client-2/Dockerfile.local'
    volumes:
      - './shared-components:/app/shared-components'
      - './app-client-2/package.json:/app/app-client-2/package.json'
      - './app-client-1/shadow-cljs.edn:/app/app-client-2/shadow-cljs.edn'
      - './app-client-1/public/assets:/app/app-client-2/public/assets'
      - './app-client-1/public/index.html:/app/app-client-2/public/index.html'
      - './app-client-1/src:/app/app-client-2/src'
    command:
      [
        "npx",
        "shadow-cljs",
        "watch",
        "app",
      ]
```
